version: 2

general:
  branches:
    only:
      - master

jobs:
  build_and_deploy:
    docker:
      - image: farwydi/go-build

    working_directory: /go/src/tg.bot
    steps:
      - checkout

      - run: make

      - run: docker build -t dominatcorp/tgbot:$CIRCLE_BRANCH /artifact
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker push dominatcorp/tgbot:$CIRCLE_BRANCH

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - master