version: 2

general:
  branches:
    only:
      - master

jobs:
  build:
    docker:
      - image: circleci/golang:1.10.2

    working_directory: /go/src/app
    steps:
      - checkout
      - setup_remote_docker

      - run: go get -v github.com/tools/godep

      - run: make

      - run: pwd
      - run: ls -la

      # - run: docker build -t dominatcorp/tgbot:$CIRCLE_BRANCH ./artifact


  # build_and_deploy:
  #   docker:
  #     - image: circleci/golang:1.10

  #   working_directory: /go/src/tg.bot
  #   steps:
  #     - checkout

  #     - run: make

  #     - save_cache:
  #         key: v1-pkg-cache
  #         paths:
  #           - "/go/pkg"

  #     - setup_remote_docker

  #     - run: docker build -t dominatcorp/tgbot:$CIRCLE_BRANCH ./artifact
  #     - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  #     - run: docker push dominatcorp/tgbot:$CIRCLE_BRANCH

workflows:
  version: 2
  conveyor:
    jobs:
      # - test:
      - build:
      # - deploy: