version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.2

    working_directory: /go/src/app
    steps:
      - checkout
      - setup_remote_docker

      - run: go get -v github.com/tools/godep

      - run: make

      - run: pwd
      - run: ls -la

workflows:
  version: 2
  conveyor:
    jobs:
      - build