version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.2

    working_directory: /go/src/app
    steps:
      - checkout

      - run: go get -v ./...

      - run: make linux

      - setup_remote_docker
      - run: docker build -t dominatcorp/tgbot:$CIRCLE_BUILD_NUM.$CIRCLE_BRANCH -t dominatcorp/tgbot:latest ./artifact
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker push dominatcorp/tgbot:$CIRCLE_BUILD_NUM.$CIRCLE_BRANCH dominatcorp/tgbot:latest

workflows:
  version: 2
  conveyor:
    jobs:
      - build