version: 2
jobs:
  build:
    docker:
      - image: farwydi/go-build

    working_directory: /go/src/github.com/dominat-corp/tg.bot
    steps:
      - checkout
      - run: make
      - store_artifacts:
          path: /go/src/github.com/dominat-corp/tg.bot/artifact